image: gcc:6.5
pipelines:
  default:
    - step:
        - 'apt-get update && apt-get install -y cmake googletest'
        - 'mkdir _build && cd _build'
        - 'cmake ..'
        - 'make check'
        - ./check
