image: gcc:latest
pipelines:
  default:
    - step:
        script:
          - 'apt-get update && apt-get install -y cmake libgtest-dev'
          - 'mkdir _build && cd _build'
          - 'cmake ..'
          - 'make check'
          - ./check
